[package]
name = "robotech"
version = "1.4.0"
edition = "2024"
authors = ["zbz"]
keywords = ["crud", "microservice", "service", "RESTful"]
description = "Backend service implementation for the RoboTech platform, providing RESTful APIs and business logic for web applications."
categories = ["web-programming::http-server"]
license = "MIT"
homepage = "https://github.com/rusthing/robotech-rs"
repository = "https://github.com/rusthing/robotech-rs"
readme = "README.md"

[features]
base = ["dep:log", "dep:tracing-log", "dep:tracing-core", "dep:tracing-subscriber", "dep:tracing-appender", "dep:thiserror", "dep:chrono", "dep:serde", "dep:serde_json", "dep:utoipa"]
api-client = ["base", "dep:reqwest"]
app = ["base", "dep:config"]
web = ["app", "dep:actix-web", "dep:actix-cors", "dep:wheel-rs", "dep:validator"]
crud = ["app", "dep:sea-orm", "dep:regex", "dep:once_cell", "dep:wheel-rs", "dep:validator"]

[dependencies]
log = { version = "0.4.29", optional = true }
tracing-log = { version = "0.2.0", optional = true }
tracing-core = { version = "0.1.36", optional = true }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json", "chrono", "tracing-log"], optional = true }
tracing-appender = { version = "0.2.4", optional = true }
config = { version = "0.15.19", optional = true }
chrono = { version = "0.4.43", optional = true }
regex = { version = "1.12.2", optional = true }
serde = { version = "1.0.228", optional = true }
serde_json = { version = "1.0.149", optional = true }
actix-web = { version = "4.12.1", optional = true }
actix-cors = { version = "0.7.1", optional = true }
sea-orm = { version = "1.1.19", optional = true }
thiserror = { version = "2.0.17", optional = true }
once_cell = { version = "1.21.3", optional = true }
validator = { version = "0.20.0", optional = true }
reqwest = { version = "0.13.1", features = ["multipart", "json", "stream"], optional = true }
utoipa = { version = "5.4.0", optional = true }
wheel-rs = { version = "1.1.1", optional = true }
[patch.crates-io]
wheel-rs = { path = "../wheel-rs", optional = true }

