[workspace]
members = ["robotech", "robotech-macros"]
resolver = "3"


[workspace.dependencies]
# rototech依赖
log = "0.4.29"
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-core = "0.1.36"
tracing-appender = "0.2.4"
tracing-subscriber = "0.3.22"
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
thiserror = "2.0.18"
chrono = "0.4.43"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
utoipa = "5.4.0"
anyhow = "1.0.101"
config = "0.15.19"
libc = "0.2.180"
regex = "1.12.3"
actix-web = "4.12.1"
actix-cors = "0.7.1"
actix-service = "2.0.3"
actix-http = "3.11.2"
rustls = "0.23.36"
socket2 = "0.6.2"
sea-orm = "1.1.19"
once_cell = "1.21.3"
validator = "0.20.0"
reqwest = "0.13.2"

idworker = "1.1.0"
wheel-rs = "1.4.0"

# macro依赖
proc-macro2 = "1.0.106"                                 # 提供与标准库 proc_macro 兼容但更易测试的接口
quote = "1.0.44"                                        # 用于将语法树转换回代码
syn = { version = "2.0.115", features = ["full"] }      # 用于解析 Rust 代码为语法树（AST）

[patch.crates-io]
idworker = { path = "../idworker" }
wheel-rs = { path = "../wheel-rs" }
