[package]
name = "robotech"
version = "1.5.0"
edition = "2024"
authors = ["zbz"]
keywords = ["crud", "microservice", "service", "RESTful"]
description = "Backend service implementation for the RoboTech platform, providing RESTful APIs and business logic for web applications."
categories = ["web-programming::http-server"]
license = "MIT"
homepage = "https://github.com/rusthing/robotech-rs"
repository = "https://github.com/rusthing/robotech-rs"
readme = "README.md"

[features]
api-client = ["dep:reqwest"]
app = ["dep:anyhow", "dep:config", "dep:libc", "dep:validator", "dep:wheel-rs"]
web = ["app", "dep:actix-web", "dep:actix-cors", "dep:actix-service", "dep:actix-http", "dep:socket2", "dep:rustls", "dep:reqwest"]
db = ["app", "dep:sea-orm", "dep:regex", "dep:once_cell"]

[dependencies]
log = "0.4.29"
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-core = "0.1.36"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json", "chrono", "tracing-log"] }
thiserror = "2.0.18"
chrono = "0.4.43"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["macros"] }
utoipa = "5.4.0"
anyhow = { version = "1.0.51", optional = true }
config = { version = "0.15.19", optional = true }
libc = { version = "0.2.180", optional = true }
regex = { version = "1.12.3", optional = true }
actix-web = { version = "4.12.1", features = ["rustls-0_23"], optional = true }
actix-cors = { version = "0.7.1", optional = true }
actix-service = { version = "2.0.3", optional = true }
actix-http = { version = "3.11.2", optional = true }
rustls = { version = "0.23.36", optional = true }
socket2 = { version = "0.6.2", optional = true }
sea-orm = { version = "1.1.19", optional = true }
once_cell = { version = "1.21.3", optional = true }
validator = { version = "0.20.0", optional = true }
reqwest = { version = "0.13.1", features = ["multipart", "json", "stream"], optional = true }

idworker = "1.1.0"
wheel-rs = { version = "1.4.0", optional = true }

[patch.crates-io]
idworker = { path = "../idworker" }
wheel-rs = { path = "../wheel-rs", optional = true }

